### ISSUE TITLE
coherent readme. this readme isn't very useful.

### ISSUE THREAD

**Issue by dominictarr** [auditdrivencrypto/private-box#1]
this readme is a design document, and at that, it needs to be tidied up.

the readme should document the properties of the cryptosystem we settled on,
but the document describing the process we went through should also be available.

**Comment by pfrazee** [comment]
+1!

**Comment by pfrazee** [comment]
@dominictarr hey could you hit this soon? It's one of our remaining todos in the docs site.

Also, do you want to keep the ADC org going? If not, I suggest we transfer this to SSBC

**Comment by dominictarr** [comment]
this is way better now, closing
