### ISSUE TITLE
can't work in browser ?

### ISSUE THREAD

**Issue by helxsz** [auditdrivencrypto/private-box#11]
I am playing private-box on the browser along with angular stack, but  private-box depends on chloride library, and chloride library can not work on the browser.

I tried to replace chloride with libsodium-wrappers', but still doesn't seem to work

**Comment by dominictarr** [comment]
no, this definitely work in the browser. chloride falls back to https://github.com/dominictarr/sodium-browserify in the browser. it will console.log a message that the bindings couldn't be loaded though.
I use browserify and it just works. I'm not sure about what happens with angular though.

**Comment by helxsz** [comment]
hi, @dominictarr, i tried again with new version of angular, it did work, my mistake !!
Thanks for the quick reply!!
